Exception on /uploaded [POST]
Traceback (most recent call last):
  File "C:\Users\CX61\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\CX61\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\CX61\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\CX61\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\CX61\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\CX61\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\machine_learning\flaskSaaS-alectrocute-master\flaskSaaS-alectrocute-master\app\views\main.py", line 20, in upload_file
    path = os.path.join(app.config['UPLOAD_FOLDER'], f.filename)
KeyError: 'UPLOAD_FOLDER'
